victoire_core:
    widgets:
        Title:
            class: "Victoire\\Widget\\TitleBundle\\Entity\\WidgetTitle"
            name: Title
            parent: Text

jms_translation:
   configs:
        victoire_title_bundle:
            dirs: ["@VictoireWidgetTitleBundle"]
            output_dir: "@VictoireWidgetTitleBundle/Resources/translations"
