victoire_cms:
    widgets:
        title:
            class: "Victoire\TitleBundle\\Entity\\WidgetTitle"
            name: title

jms_translation:
    configs:
        victoire_title_bundle:
            dirs: ["@VictoireTitleBundle"]
            output_dir: "@VictoireTitleBundle/Resources/translations"
