services:
    victoire_core.twig.widget_title_manager:
        class: Victoire\TitleBundle\Widget\Manager\WidgetTitleManager
        arguments: [@service_container]

    widget_title_manager:
        alias: victoire_core.twig.widget_title_manager
