services:
    victoire_core.widget_title_content_resolver:
        parent: victoire_core.widget_text_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Title }
    #alias to the entity
    victoire.widget.title:
        class: Victoire\Widget\TitleBundle\Entity\WidgetTitle
    #alias to the form
    victoire.widget.form.title:
        class: Victoire\Widget\TitleBundle\Form\WidgetTitleType
        tags:
            - { name: form.type , alias: victoire_widget_form_title}
